const funnyDrinkGroupNames: string[] = [
    "Team Uống Xuyên Vũ Trụ",
    "Hội Thở Bằng Trà Sữa",
    "Cú Đêm Gọi Cà Phê",
    "Order Là Đạo",
    "Team Nghiện Trân Châu",
    "Hội Gục Ngã Vì Đá Xay",
    "Sống Vì Matcha",
    "Team Không Đường Không Vui",
    "Nhóm Cà Phê Sữa Đá Quốc Dân",
    "Thèm Là Phải Uống",
    "Cà Phê Là Chân Ái",
    "Team Bất Ổn Nhưng Gọi Nhiệt",
    "Đừng Hỏi Sao Mập",
    "Uống Tới Lúc Mặt Nhăn",
    "Trà Sữa Còn – Hy Vọng Còn",
    "Team Cà Phê Không Đường Nhưng Tình Có Muối",
    "Hội Đập Đá Có Văn Hóa",
    "Gọi Ly Đá Xay Để Xua Tan Mọi Căng Thẳng",
    "Hội Gọi Mỗi Ngày Một Loại",
    "Uống Cho Quên Hết Deadline",
    "Hội Uống Đều Như Deadline",
    "Team Gọi Đúng Cỡ Đại",
    "Đừng Uống Một Mình",
    "Hội Đồng Uống Của Vũ Trụ",
    "Team Lười Nhưng Uống Nhiệt",
    "Thích Gì Gọi Đó",
    "Chưa Uống Là Chưa Tỉnh",
    "Uống Để Tỉnh Cả Ngày",
    "Team Sáng Trà Chiều Cà",
    "Bụng Không Đói Nhưng Miệng Thèm",
    "Chốt Đơn Mỗi Giờ",
    "Nhóm Gọi Không Cần Lý Do",
    "Order Còn Nhanh Hơn Cảm Xúc",
    "Sống Như Cốc Đầy Đá",
    "Người Ta Gọi Tình – Mình Gọi Trà",
    "Cà Phê Không Làm Ta Buồn Ngủ, Chỉ Làm Ta Run",
    "Trà Sữa Gây Nghiện – Nhóm Gây Cười",
    "Đặt Đồ Như Hơi Thở",
    "Ngừng Gọi Trà – Tụi Mình Không Làm Được",
    "Hội Uống Để Sống",
    "Cà Phê Là Chuyện Nhỏ – Gọi Hàng Là Chuyện Lớn",
    "Gọi Mỗi Ngày – Uống Mỗi Giờ",
    "Uống Vào Là Vào Mood",
    "Đồ Uống Hơn Người Yêu",
    "Hội Lạnh Ngoài Da – Nóng Trong Cốc",
    "Nạp Đường Để Đủ Tình Người",
    "Sống Không Trà – Cảm Thấy Sai Sai",
    "Deadline Tới – Uống Để Quên",
    "Mỗi Ly Một Tâm Trạng",
    "Team 90% Đường 100% Drama",
    "Nhóm Yêu Trà Sữa Hơn Crush",
    "Cà Phê Sống Còn – Code Vẫn Chạy",
    "Uống Là Mở Lòng",
    "Mỗi Đơn Một Niềm Vui",
    "Trà Sữa Là Tình Yêu Thứ Ba",
    "Sống Có Tâm – Gọi Có Trà",
    "Cốc Này Cho Đời Tươi",
    "Mệt Đâu Quan Trọng – Trà Sữa Quan Trọng",
    "Deadline Gọi – Tụi Mình Gọi Lại",
    "Nghĩ Là Uống – Không Nghĩ Cũng Uống",
    "Order Tự Nhiên Như Hơi Thở",
    "Tình Bạn Bền Như Đá Viên",
    "Chỉ Cần Cà Phê Là Ổn",
    "Không Có Gì Ngoài Đường Và Đá",
    "Code Bug Cỡ Nào – Cà Phê Lo",
    "Team Tán Gẫu Cùng Trà",
    "Đặt Đồ Là Mỗi Ngày",
    "Tình Chết Nhưng Ly Trà Còn",
    "Deadline Đến Sau Ly Trà",
    "Mỗi Người Một Cốc – Một Tình Cảm",
    "Hội Cà Phê Không Phanh",
    "Đừng Rủ Ăn – Rủ Gọi Uống",
    "Uống Cho Gọi Là Bạn",
    "Thèm Là Gọi – Không Cần Lý Do",
    "Sống Là Đặt Trà",
    "Thức Vì Cà Phê – Chứ Không Vì Em",
    "Team Gọi Xong Mới Nghĩ",
    "Hội Không Gọi Không Ngồi",
    "Uống Hết Cốc Là Cười Tươi",
    "Tập Trung Cà Phê – Không Drama",
    "Uống Là Gắn Bó",
    "Ly Sau Đuổi Ly Trước",
    "Nhóm Gọi Xong Mới Tỉnh",
    "Cà Phê Cũng Phải Có Đội",
    "Uống Một Mình Là Cô Đơn",
    "Team Có Ly Là Có Mood",
    "Cốc Này Vì Hôm Qua Buồn",
    "Order Có Tâm – Nhận Cốc Có Tình",
    "Uống Là Đam Mê – Nhóm Là Nhà",
    "Tình Trôi Nhưng Trân Châu Ở Lại",
    "Tự Hào Là Hội Gọi Sớm",
    "Hội Lựa Kỹ Uống Dai",
    "Mỗi Ly Một Cảm Xúc",
    "Không Có Ly – Không Có Ngày",
    "Nhóm Yêu Ly Dài",
    "Mỗi Lần Gọi – Mỗi Lần Cười",
    "Thích Trà Sữa Hơn Drama",
    "Đặt Trà Là Nghệ Thuật",
    "Team Uống Là Có Lời",
    "Ly Là Đời – Không Ly Không Vui",
    "Nhóm Gọi Không Bỏ Sót Ai",
    "Không Có Trà – Không Có Tôi",
    "Order Đúng Lúc – Mood Đúng Gu",
    "Team Đá Xay Đến Chết",
    "Không Đường Cũng Phải Gọi",
    "Team Yêu Cà Phê Như Crush",
    "Không Gọi – Không Được",
    "Đặt Là Có – Chờ Là Có Vui",
    "Trà Sữa Là Lý Do Tập Trung",
    "Order Nhiều – Gần Nhau Hơn",
    "Cốc Trà Cứu Tâm Trạng",
    "Nhóm Gọi Có Lý",
    "Cốc Trà – Tình Bạn",
    "Nhóm Gọi Nhanh Như Chớp",
    "Cốc Này Cho Em – Cốc Kia Cho Ai",
    "Team Thèm Gì Gọi Nấy",
    "Cà Phê Là Ánh Sáng Cuộc Đời",
    "Team Sáng Đặt – Chiều Nhận",
    "Nhóm Có Gu Uống",
    "Team Luôn Có Ly Trong Tay",
    "Uống Là Nói Nhiều",
    "Trà Sữa Là Cầu Nối",
    "Chúng Tôi Gọi Vui Vẻ",
    "Gọi Không Hối Tiếc",
    "Uống Xong Mới Làm",
    "Ly Nhẹ – Tình Đậm",
    "Team Gọi Lúc 3 Giờ Sáng",
    "Uống Cho Đầy Năng Lượng",
    "Không Có Trà – Không Có Sáng",
    "Hội Uống Chuyên Nghiệp",
    "Đặt Cốc – Làm Nhiệm Vụ",
    "Team Gọi Là Có",
    "Mỗi Lần Đặt – Một Kỷ Niệm",
    "Nhóm Gọi Theo Mood",
    "Đặt Trà Giao Tiếp",
    "Team Hút Là Quên Sầu",
    "Hội Gọi Nhẹ – Không Gây Sốc",
    "Không Cốc – Không Code",
    "Gọi Để Tồn Tại",
    "Trà Sữa Là Lý Do Mỉm Cười",
    "Hội Đồng Gọi Cà Phê",
    "Team Uống Đều Tay",
    "Cà Phê – Gắn Bó Lâu Dài",
    "Nhóm Này Là Của Ly",
    "Gọi Là Nghệ Thuật",
    "Hội Đam Mê Gọi Ship",
    "Team Gọi Gì Cũng Được",
    "Đặt Gì Thì Cũng Vui",
    "Uống Cho Tròn Buổi",
    "Trà Sữa Là Niềm Tin",
    "Uống Là Có Gắn Kết",
    "Gọi Là Đam Mê",
    "Chúng Tôi Là Người Gọi Trà",
    "Nhóm Nghiện Ly Nhựa",
    "Team Uống Mỗi Giờ",
    "Cốc Sau Cứu Cốc Trước",
    "Ly Trà Là Tâm Hồn",
    "Team Gọi Vẫn Vui",
    "Cốc Này Cho Cuộc Đời",
    "Chúng Tôi Là Gọi Nhanh",
    "Team Có Trà Có Tình",
    "Hội Gọi Mỗi Buổi",
    "Gọi Để Gần Hơn",
    "Team Đặt Cho Vui",
    "Team Luôn Full Topping",
    "Trà Sữa Là Sợi Dây Kết Nối",
    "Đặt Để Sống",
    "Không Ly – Không Gặp",
    "Gọi Là Kết Nghĩa",
    "Trà Này – Tình Đây",
    "Team Đặt Là Chill",
    "Hội Đồng Ly",
    "Trà Sữa Là Chân Ái",
    "Team Vui Là Gọi",
    "Cốc Trà – Hội Bạn",
    "Gọi Gì Cũng Thành Team",
    "Hội Yêu Đá",
    "Team Chốt Ly Nhanh Như Gió",
    "Hội Trà Đá",
    "Đom Đóm",
    "Đen Đá Không Đường",
    "FC Khát Nước",
    "Giải Nhiệt",
    "Nối Vòng Tay Lớn",
    "Săn Sale",
    "5l Nước",
    "Hết Tiền Vì Đam Mê"
];
export default funnyDrinkGroupNames;