const funnyDrinkGroupNames: string[] = [
    "Sống Vì Matcha",
    "Thèm Là Phải Uống",
    "Đừng Uống Một Mình",
    "Thích Gì Gọi Đó",
    "Chốt Đơn Mỗi Giờ",
    "Hội Uống Để Sống",
    "Hội Trà Đá",
    "Đom Đóm",
    "Đen Đá Không Đường",
    "FC Khát Nước",
    "Giải Nhiệt",
    "Nối Vòng Tay Lớn",
    "Săn Sale",
    "5l Nước",
    "Hết Tiền Vì Đam Mê",
    "Hết Tiền",
    "Đặt Hộ",
    "Nhanh Nào",
    "Gọi Liền",
    "Đủ Mặt",
    "Order Nha",
    "Gọi Trước",
    "Ship Về",
    "Chốt Deal",
    "Mê Ly",
    "Hốt Trà",
    "Não To",
    "Chốt Nhanh",
    "Mặt Trời",
    "Trái Đất",
    "Thám Tử",
    "Code Dạo",
    "Bug Fix",
    "No Bug",
    "Tỉnh Táo",
    "Thở Oxy",
    "Bubble",
    "Latte",
    "Fire",
    "Chill",
    "Honey",
    "Sugar",
    "Breeze",
    "Storm",
    "Flash",
    "Dream",
    "Boost",
    "Happy",
    "Smile",
    "Angel",
    "Ghost",
    "Mood",
    "Snap",
    "Cozy",
    "Peace",
    "Bliss",
    "Drama",
    "Nước Sôi",
    "Lắc Đều",
    "Siêu nhân",
    "Tóp Tóp",
    "Glug Glug",
    "Trân châu",
    "Buổi sáng",
    "Buổi trưa",
    "Tăng ca",
    "Nhâm Nhi",
    "Giải Nhiệt Trưa",
    "Cần Nước",
    "Buồn ngủ",
    "Cà Phê Zoom",
    "Sữa Đậu Jira",
    "Chill Văn Phòng",
    "Trà xanh",
    "Idol",
    "Trình là gì",
    "No money",
    "Tiết kiệm",
    "Nước ép",
    "Người đẹp",
    "Team phố",
];
export default funnyDrinkGroupNames;